### PR TITLE
Fallback emojis

### PR DESCRIPTION
**Pull request by GNURub**
Using twemoji to use like fallback

### CODE REVIEW

**Comment by ahkohd** [comment]
Hi, @GNURub thanks for your wonderful contribution. Can you provide a demo?

**Review by ahkohd — COMMENTED** [review]
Hi, @GNURub thanks for your wonderful contribution. Can you provide a demo, i.e share a screenshot of the fallback in action?

**Comment by GNURub** [comment]
With fallback (unsupported browser):
image

Native:
image

**Comment by ahkohd** [comment]
@GNURub thanks! This is very nice. I'll let you know when the updates are on **NPM**.

**Comment by ahkohd** [comment]
@all-contributors please add @GNURub for adding new feature of using emoji as fallback emojis.

**Comment by ahkohd** [comment]
@all-contributors please add @GNURub for code.

**Comment by ahkohd** [comment]
🎉 I have published **ngx-emoji-picker@0.1.6**
```bash
npm i ngx-emoji-picker twemoji
```

**Pull request merged**
